"""PPTX tool for generating PowerPoint presentations."""

from typing import Any

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    PPTX_AVAILABLE = True
except ImportError:
    PPTX_AVAILABLE = False


class PptxTool:
    """Tool for generating PowerPoint presentations."""

    def __init__(self):
        if not PPTX_AVAILABLE:
            raise ImportError("python-pptx is not installed. Install with: pip install python-pptx")

    async def create(
        self,
        slides: list[dict[str, Any]],
        output_path: str = "presentation.pptx",
        title: str = "Presentation",
    ) -> str:
        """Create a PowerPoint presentation.

        Args:
            slides: List of slide definitions
                Each slide can have:
                - title: Slide title
                - content: List of content lines
                - bullets: List of bullet points
            output_path: Output file path
            title: Presentation title

        Returns:
            Success or error message
        """
        try:
            prs = Presentation()

            # Set title slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title = slide.shapes.title
            subtitle = slide.placeholders[1]
            title.text = title
            subtitle.text = "Generated by SwarmMind"

            # Add content slides
            for slide_data in slides:
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)

                # Set title
                shapes = slide.shapes
                title_shape = shapes.title
                title_shape.text = slide_data.get("title", "Slide")

                # Set content
                body_shape = shapes.placeholders[1]
                tf = body_shape.text_frame
                tf.clear()

                # Add bullets
                bullets = slide_data.get("bullets", [])
                content = slide_data.get("content", [])

                items = bullets if bullets else content

                for i, item in enumerate(items):
                    if i == 0:
                        tf.text = str(item)
                    else:
                        p = tf.add_paragraph()
                        p.text = str(item)
                        p.level = 0

            # Save
            prs.save(output_path)
            return f"Presentation created: {output_path}"

        except Exception as e:
            return f"Error creating presentation: {str(e)}"

    async def add_slide(
        self,
        presentation_path: str,
        title: str,
        content: list[str],
    ) -> str:
        """Add a slide to an existing presentation.

        Args:
            presentation_path: Path to existing presentation
            title: Slide title
            content: List of content lines

        Returns:
            Success or error message
        """
        try:
            prs = Presentation(presentation_path)

            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)

            # Set title
            shapes = slide.shapes
            title_shape = shapes.title
            title_shape.text = title

            # Set content
            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            tf.clear()

            for i, item in enumerate(content):
                if i == 0:
                    tf.text = item
                else:
                    p = tf.add_paragraph()
                    p.text = item
                    p.level = 0

            prs.save(presentation_path)
            return f"Slide added to: {presentation_path}"

        except Exception as e:
            return f"Error adding slide: {str(e)}"


# Tool function for AgentScope
async def generate_pptx(
    slides: list[dict[str, Any]],
    output_path: str = "presentation.pptx",
    title: str = "Presentation",
) -> str:
    """Generate a PowerPoint presentation.

    Args:
        slides: List of slides. Each slide can have:
            - title: Slide title (str)
            - bullets: Bullet points (list[str])
            - content: Plain content (list[str])
        output_path: Output file path
        title: Presentation title

    Returns:
        Success or error message
    """
    if not PPTX_AVAILABLE:
        return "Error: python-pptx not installed. Install with: pip install python-pptx"

    tool = PptxTool()
    return await tool.create(slides, output_path, title)
