"""First-round planner implementation."""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass, field
from typing import Any

from agentscope.message import Msg
from pydantic import BaseModel, ConfigDict, Field

from swarmmind.agents.profile import AgentProfileStore
from swarmmind.agents.config import AgentConfig, AgentScopeConfig
from swarmmind.agents.factory import AgentFactory
from swarmmind.memory import LongTermMemoryBase
from swarmmind.models.capability import AgentRole, DEFAULT_ROLE_TOOL_GROUPS, DEFAULT_STRATEGY_PROFILES, ToolGroup
from swarmmind.models.run import Run
from swarmmind.models.task import SubTask, Task
from swarmmind.prompt_template import (
    PLANNER_SYSTEM_PROMPT,
    PLANNER_TASK_DECOMPOSITION_PROMPT,
    PromptTemplate,
    render_prompt,
)


PLANNER_ALLOWED_ROLES: set[AgentRole] = {
    AgentRole.PLANNER,
    AgentRole.CODER,
    AgentRole.TESTER,
    AgentRole.REVIEWER,
    AgentRole.RESEARCHER,
    AgentRole.WRITER,
    AgentRole.EXECUTOR,
}


@dataclass(slots=True)
class _NormalizedPlanSubtaskSpec:
    name: str
    description: str
    agent_profile_id: str | None
    role: AgentRole
    preferred_strategy: str | None
    required_tool_groups: list[ToolGroup]
    sandbox_profile: str | None
    acceptance_criteria: list[str]
    dependencies: list[str]
    metadata: dict[str, Any] = field(default_factory=dict)


class Planner:
    """Create a simple task graph from the submitted goal."""

    def __init__(
        self,
        model_name: str = "gpt-4o",
        model_api_key: str | None = None,
        model_base_url: str | None = None,
        model_temperature: float = 0.2,
        model_max_tokens: int = 2048,
        system_prompt_template: PromptTemplate = PLANNER_SYSTEM_PROMPT,
        user_prompt_template: PromptTemplate = PLANNER_TASK_DECOMPOSITION_PROMPT,
        agent_profile_store: AgentProfileStore | None = None,
        long_term_memory: LongTermMemoryBase | None = None,
    ) -> None:
        self._model_name = model_name
        self._model_api_key = model_api_key
        self._model_base_url = model_base_url
        self._model_temperature = model_temperature
        self._model_max_tokens = model_max_tokens
        self._system_prompt_template = system_prompt_template
        self._user_prompt_template = user_prompt_template
        self._agent_profile_store = agent_profile_store
        self._long_term_memory = long_term_memory

    async def plan(self, task: Task, run: Run) -> list[SubTask]:
        """Return a task graph generated by model when available, with deterministic fallback."""
        llm_subtasks = await self._plan_with_model(task, run)
        if llm_subtasks:
            return llm_subtasks
        return self._plan_with_rules(task, run)

    async def _plan_with_model(self, task: Task, run: Run) -> list[SubTask] | None:
        if not self._model_name:
            return None
        if not self._model_api_key and not self._model_base_url:
            return None

        try:
            agent_factory = AgentFactory(
                AgentConfig(
                    name="planner-agent",
                    scope_config=AgentScopeConfig(
                        model_name=self._model_name,
                        api_key=self._model_api_key,
                        base_url=self._model_base_url,
                        temperature=self._model_temperature,
                        max_tokens=self._model_max_tokens,
                    ),
                    max_steps=6,
                    system_prompt=render_prompt(self._system_prompt_template),
                    skill_profiles=["task_planning"],
                )
            )
            agent = agent_factory.create_main_agent(tools=[])
            prompt = await self._compose_planning_prompt(task)
            result = await agent(Msg(name="user", role="user", content=prompt))
            text = result.get_text_content() or json.dumps(result.to_dict(), ensure_ascii=False)
            payload = self._extract_json_payload(text)
            if payload is None:
                return None

            plan_result = _PlanResult.model_validate(payload)
            normalized_plan = self._validate_and_normalize_plan(task, plan_result)
            return self._build_subtasks_from_plan(task, run, normalized_plan)
        except Exception:
            return None

    async def _compose_planning_prompt(self, task: Task) -> str:
        prompt = render_prompt(
            self._user_prompt_template,
            {
                "task_goal": task.goal,
                "constraints_json": json.dumps(task.constraints, ensure_ascii=False),
                "profile": str(task.metadata.get("profile", "py-basic")),
                "preferred_strategy": str(task.metadata.get("preferred_strategy") or "build_app"),
                "agent_profiles_json": json.dumps(self._render_agent_profile_options(), ensure_ascii=False),
            },
        )
        memory_context = await self._render_memory_context(task.goal)
        if not memory_context:
            return prompt
        return f"{prompt}\n\nRelevant long-term memory:\n{memory_context}"

    async def _render_memory_context(self, query: str) -> str:
        if self._long_term_memory is None:
            return ""
        try:
            items = await self._long_term_memory.retrieve(query, top_k=3)
        except Exception:
            return ""
        if not items:
            return ""
        return "\n".join(f"- {item.content[:280]}" for item in items)

    @staticmethod
    def _extract_json_payload(raw_text: str) -> dict[str, object] | None:
        fenced = re.search(r"```(?:json)?\\s*(\{.*\})\\s*```", raw_text, flags=re.DOTALL | re.IGNORECASE)
        candidate = fenced.group(1) if fenced else raw_text
        start = candidate.find("{")
        end = candidate.rfind("}")
        if start == -1 or end == -1 or end < start:
            return None
        snippet = candidate[start : end + 1]
        try:
            value = json.loads(snippet)
        except json.JSONDecodeError:
            return None
        if isinstance(value, dict):
            return value
        return None

    def _validate_and_normalize_plan(self, task: Task, plan_result: "_PlanResult") -> list[_NormalizedPlanSubtaskSpec]:
        return [self._normalize_plan_subtask(task, spec) for spec in plan_result.subtasks]

    def _build_subtasks_from_plan(
        self,
        task: Task,
        run: Run,
        plan_result: "_PlanResult | list[_NormalizedPlanSubtaskSpec]",
    ) -> list[SubTask]:
        normalized_specs = (
            self._validate_and_normalize_plan(task, plan_result)
            if isinstance(plan_result, _PlanResult)
            else plan_result
        )

        normalized: list[tuple[str, _NormalizedPlanSubtaskSpec]] = []
        used_names: set[str] = set()

        for spec in normalized_specs:
            normalized_name = self._normalize_name(spec.name)
            if not normalized_name:
                normalized_name = "subtask"
            base_name = normalized_name
            suffix = 2
            while normalized_name in used_names:
                normalized_name = f"{base_name}-{suffix}"
                suffix += 1
            used_names.add(normalized_name)
            normalized.append((normalized_name, spec))

        name_to_id = {name: str(uuid.uuid4()) for name, _ in normalized}
        subtasks: list[SubTask] = []

        for name, spec in normalized:
            dependencies = [name_to_id[d] for d in spec.dependencies if d in name_to_id and d != name]
            acceptance_criteria = [item.strip() for item in spec.acceptance_criteria if item.strip()]
            if not acceptance_criteria:
                acceptance_criteria = ["Subtask output is complete and verifiable."]
            resolved_strategy = spec.preferred_strategy or self._default_strategy_for_role(spec.role)
            resolved_agent_profile_id, resolution_warnings = self._resolve_agent_profile_id(
                role=spec.role,
                requested_profile_id=spec.agent_profile_id,
                preferred_strategy=resolved_strategy,
            )
            metadata = {
                "run_id": run.id,
                "plan_source": "llm",
                "planning_prompt": self._user_prompt_template.name,
                **spec.metadata,
            }
            warnings = list(metadata.get("planner_validation_warnings") or [])
            warnings.extend(resolution_warnings)
            if warnings:
                metadata["planner_validation_warnings"] = warnings
            if metadata.get("original_agent_profile_id") is None and spec.agent_profile_id != resolved_agent_profile_id:
                metadata["original_agent_profile_id"] = spec.agent_profile_id
            metadata["resolved_agent_profile_id"] = resolved_agent_profile_id
            metadata["normalized_tool_groups"] = [tool_group.value for tool_group in spec.required_tool_groups]

            subtasks.append(
                SubTask(
                    id=name_to_id[name],
                    task_id=task.id,
                    name=name,
                    description=spec.description.strip() or f"Execute {name}",
                    agent_profile_id=resolved_agent_profile_id,
                    role=spec.role,
                    preferred_strategy=resolved_strategy,
                    required_tool_groups=spec.required_tool_groups,
                    sandbox_profile=spec.sandbox_profile or task.metadata.get("profile", "py-basic"),
                    acceptance_criteria=acceptance_criteria,
                    dependencies=dependencies,
                    metadata=metadata,
                )
            )

        return subtasks

    def _normalize_plan_subtask(self, task: Task, spec: "_PlanSubtaskSpec") -> _NormalizedPlanSubtaskSpec:
        warnings: list[str] = []
        metadata: dict[str, Any] = {}

        original_role = spec.role
        original_strategy = spec.preferred_strategy
        original_agent_profile_id = spec.agent_profile_id
        original_sandbox_profile = spec.sandbox_profile

        requested_profile_id = self._normalize_optional_string(spec.agent_profile_id)
        if requested_profile_id != spec.agent_profile_id:
            warnings.append("Normalized empty agent_profile_id to null.")
            metadata["original_agent_profile_id"] = spec.agent_profile_id

        sandbox_profile = self._normalize_optional_string(spec.sandbox_profile)
        if sandbox_profile != spec.sandbox_profile:
            warnings.append("Normalized empty sandbox_profile to null.")
            metadata["original_sandbox_profile"] = spec.sandbox_profile

        role = self._parse_role(spec.role)
        if spec.role and (spec.role.strip().lower() != role.value or role not in PLANNER_ALLOWED_ROLES):
            warnings.append(f"Normalized invalid planner role '{spec.role}' to '{role.value}'.")
            metadata["original_role"] = original_role
        elif role not in PLANNER_ALLOWED_ROLES:
            warnings.append(f"Planner role '{role.value}' is not supported for subtasks; using 'coder'.")
            metadata["original_role"] = original_role
            role = AgentRole.CODER

        preferred_strategy = self._normalize_preferred_strategy(spec.preferred_strategy, role, task, warnings, metadata)
        role = self._align_role_with_strategy(role, preferred_strategy, requested_profile_id, warnings, metadata)

        tool_groups = self._parse_tool_groups(spec.required_tool_groups)
        invalid_tool_groups = [
            str(value).strip() for value in spec.required_tool_groups if str(value).strip().lower() not in {group.value for group in ToolGroup}
        ]
        if invalid_tool_groups:
            warnings.append(
                f"Removed unsupported tool groups: {', '.join(invalid_tool_groups)}."
            )
        if not tool_groups:
            tool_groups = self._default_tool_groups_for_role(role)
            warnings.append(f"Fell back to default tool groups for role '{role.value}'.")

        if original_strategy != preferred_strategy and original_strategy is not None:
            metadata.setdefault("original_preferred_strategy", original_strategy)
        if original_role != role.value:
            metadata.setdefault("original_role", original_role)
        if original_agent_profile_id != requested_profile_id and original_agent_profile_id is not None:
            metadata.setdefault("original_agent_profile_id", original_agent_profile_id)
        if original_sandbox_profile != sandbox_profile and original_sandbox_profile is not None:
            metadata.setdefault("original_sandbox_profile", original_sandbox_profile)
        if warnings:
            metadata["planner_validation_warnings"] = warnings

        return _NormalizedPlanSubtaskSpec(
            name=spec.name,
            description=spec.description,
            agent_profile_id=requested_profile_id,
            role=role,
            preferred_strategy=preferred_strategy,
            required_tool_groups=tool_groups,
            sandbox_profile=sandbox_profile,
            acceptance_criteria=spec.acceptance_criteria,
            dependencies=spec.dependencies,
            metadata=metadata,
        )

    @staticmethod
    def _parse_role(value: str | None) -> AgentRole:
        if not value:
            return AgentRole.CODER
        try:
            role = AgentRole(str(value).strip().lower())
        except ValueError:
            return AgentRole.CODER
        if role not in PLANNER_ALLOWED_ROLES:
            return AgentRole.CODER
        return role

    @staticmethod
    def _parse_tool_groups(values: list[str]) -> list[ToolGroup]:
        parsed: list[ToolGroup] = []
        for value in values:
            token = str(value).strip().lower()
            try:
                tool_group = ToolGroup(token)
            except ValueError:
                continue
            if tool_group not in parsed:
                parsed.append(tool_group)
        return parsed

    @staticmethod
    def _default_tool_groups_for_role(role: AgentRole) -> list[ToolGroup]:
        return list(DEFAULT_ROLE_TOOL_GROUPS.get(role, [ToolGroup.PROJECT_READ]))

    @staticmethod
    def _normalize_name(name: str) -> str:
        token = (name or "").strip().lower()
        token = re.sub(r"[^a-z0-9]+", "-", token)
        token = token.strip("-")
        return token

    def _render_agent_profile_options(self) -> list[dict[str, str | bool | None]]:
        if self._agent_profile_store is None:
            return []
        return [
            {
                "id": profile.id,
                "role": profile.role.value,
                "default_strategy": profile.default_strategy,
                "allow_handoff": profile.handoff_policy.allow_handoff,
            }
            for profile in self._agent_profile_store.list_all()
        ]

    def _resolve_agent_profile_id(
        self,
        *,
        role: AgentRole,
        requested_profile_id: str | None,
        preferred_strategy: str | None,
    ) -> tuple[str | None, list[str]]:
        warnings: list[str] = []
        if self._agent_profile_store is None:
            return requested_profile_id, warnings
        if requested_profile_id:
            requested_profile = self._agent_profile_store.get(requested_profile_id)
            if requested_profile is None:
                warnings.append(f"Requested agent profile '{requested_profile_id}' does not exist; using role default.")
            elif requested_profile.role not in {role, AgentRole.EXECUTOR}:
                warnings.append(
                    f"Requested agent profile '{requested_profile_id}' is incompatible with role '{role.value}'; using a compatible profile."
                )
            else:
                return requested_profile.id, warnings

        profile = self._agent_profile_store.resolve_for_subtask(
            profile_id=None,
            role=role,
            preferred_strategy=preferred_strategy,
        )
        return profile.id, warnings

    @staticmethod
    def _normalize_optional_string(value: str | None) -> str | None:
        if value is None:
            return None
        token = str(value).strip()
        return token or None

    def _normalize_preferred_strategy(
        self,
        value: str | None,
        role: AgentRole,
        task: Task,
        warnings: list[str],
        metadata: dict[str, Any],
    ) -> str | None:
        normalized = self._normalize_optional_string(value)
        if normalized != value:
            warnings.append("Normalized empty preferred_strategy to null.")
            metadata["original_preferred_strategy"] = value
        if normalized and normalized in DEFAULT_STRATEGY_PROFILES:
            return normalized
        if normalized:
            warnings.append(f"Normalized unsupported preferred_strategy '{normalized}' to a compatible default.")
            metadata["original_preferred_strategy"] = value
        task_strategy = self._normalize_optional_string(task.metadata.get("preferred_strategy"))
        if task_strategy and task_strategy in DEFAULT_STRATEGY_PROFILES:
            return task_strategy
        return self._default_strategy_for_role(role)

    def _align_role_with_strategy(
        self,
        role: AgentRole,
        preferred_strategy: str | None,
        requested_profile_id: str | None,
        warnings: list[str],
        metadata: dict[str, Any],
    ) -> AgentRole:
        if not preferred_strategy:
            return role
        strategy_profile = DEFAULT_STRATEGY_PROFILES.get(preferred_strategy)
        if strategy_profile is None or not strategy_profile.recommended_roles:
            return role
        if role in strategy_profile.recommended_roles:
            return role

        candidate_role = strategy_profile.recommended_roles[0]
        if requested_profile_id and self._agent_profile_store is not None:
            profile = self._agent_profile_store.get(requested_profile_id)
            if profile is not None and profile.role in strategy_profile.recommended_roles:
                candidate_role = profile.role

        warnings.append(
            f"Normalized role '{role.value}' to '{candidate_role.value}' for preferred_strategy '{preferred_strategy}'."
        )
        metadata.setdefault("original_role", role.value)
        return candidate_role

    @staticmethod
    def _default_strategy_for_role(role: AgentRole) -> str:
        role_defaults = {
            AgentRole.PLANNER: "task_planning",
            AgentRole.CODER: "build_app",
            AgentRole.TESTER: "verification",
            AgentRole.REVIEWER: "review",
            AgentRole.RESEARCHER: "research",
            AgentRole.WRITER: "write_report",
            AgentRole.EXECUTOR: "build_app",
        }
        return role_defaults.get(role, "build_app")

    def _plan_with_rules(self, task: Task, run: Run) -> list[SubTask]:
        goal = task.goal.lower()
        needs_verification = "test" in goal or any(token in task.goal for token in ("测试", "验证"))
        subtasks: list[SubTask] = []
        planner_profile_id, _ = self._resolve_agent_profile_id(
            role=AgentRole.PLANNER,
            requested_profile_id=task.metadata.get("agent_profile_id"),
            preferred_strategy="task_planning",
        )

        analyze_subtask = SubTask(
            id=str(uuid.uuid4()),
            task_id=task.id,
            name="analyze-requirement",
            description="Analyze the goal and identify the implementation scope.",
            agent_profile_id=planner_profile_id,
            role=AgentRole.PLANNER,
            preferred_strategy="task_planning",
            required_tool_groups=[ToolGroup.PROJECT_READ],
            acceptance_criteria=["The implementation scope is summarized clearly."],
            metadata={"run_id": run.id, "plan_source": "rules"},
        )
        subtasks.append(analyze_subtask)

        build_tool_groups = [ToolGroup.PROJECT_READ, ToolGroup.PROJECT_WRITE, ToolGroup.SANDBOX_EXEC]
        if needs_verification:
            build_tool_groups.append(ToolGroup.ARTIFACT_READ)
        coder_profile_id, _ = self._resolve_agent_profile_id(
            role=AgentRole.CODER,
            requested_profile_id=task.metadata.get("agent_profile_id"),
            preferred_strategy=task.metadata.get("preferred_strategy") or "build_app",
        )

        implementation_subtask = SubTask(
            id=str(uuid.uuid4()),
            task_id=task.id,
            name="prepare-implementation",
            description=f"Prepare the implementation steps for: {task.goal}",
            agent_profile_id=coder_profile_id,
            role=AgentRole.CODER,
            preferred_strategy=task.metadata.get("preferred_strategy") or "build_app",
            required_tool_groups=build_tool_groups,
            sandbox_profile=task.metadata.get("profile", "py-basic"),
            acceptance_criteria=["The execution plan references the right tool groups."],
            dependencies=[analyze_subtask.id],
            metadata={"run_id": run.id, "plan_source": "rules"},
        )
        subtasks.append(implementation_subtask)

        if needs_verification:
            tester_profile_id, _ = self._resolve_agent_profile_id(
                role=AgentRole.TESTER,
                requested_profile_id=task.metadata.get("agent_profile_id"),
                preferred_strategy="verification",
            )
            verify_subtask = SubTask(
                id=str(uuid.uuid4()),
                task_id=task.id,
                name="verify-result",
                description="Verify the implementation using the declared acceptance criteria.",
                agent_profile_id=tester_profile_id,
                role=AgentRole.TESTER,
                preferred_strategy="verification",
                required_tool_groups=[ToolGroup.SANDBOX_EXEC, ToolGroup.ARTIFACT_READ],
                sandbox_profile=task.metadata.get("profile", "py-basic"),
                acceptance_criteria=["Verification evidence is attached to the run."],
                dependencies=[implementation_subtask.id],
                metadata={"run_id": run.id, "plan_source": "rules"},
            )
            reviewer_profile_id, _ = self._resolve_agent_profile_id(
                role=AgentRole.REVIEWER,
                requested_profile_id=task.metadata.get("agent_profile_id"),
                preferred_strategy="review",
            )
            review_subtask = SubTask(
                id=str(uuid.uuid4()),
                task_id=task.id,
                name="review-result",
                description="Review verification evidence and decide whether to accept or rework.",
                agent_profile_id=reviewer_profile_id,
                role=AgentRole.REVIEWER,
                preferred_strategy="review",
                required_tool_groups=[ToolGroup.ARTIFACT_READ, ToolGroup.MEMORY_LOOKUP],
                acceptance_criteria=["A structured review decision is attached to the run."],
                dependencies=[verify_subtask.id],
                metadata={"run_id": run.id, "plan_source": "rules"},
            )
            subtasks.extend([verify_subtask, review_subtask])

        return subtasks


class _PlanSubtaskSpec(BaseModel):
    name: str = Field(...)
    description: str = Field(default="")
    agent_profile_id: str | None = Field(default=None)
    role: str = Field(default="coder")
    model_config = ConfigDict(populate_by_name=True)

    preferred_strategy: str | None = Field(default=None)
    required_tool_groups: list[str] = Field(default_factory=list)
    sandbox_profile: str | None = Field(default=None)
    acceptance_criteria: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)

class _PlanResult(BaseModel):
    subtasks: list[_PlanSubtaskSpec] = Field(default_factory=list)
