"""First-round planner implementation."""

from __future__ import annotations

import json
import re
import uuid

from agentscope.message import Msg
from pydantic import BaseModel, Field

from swarmmind.agents.config import AgentConfig, AgentScopeConfig
from swarmmind.agents.factory import AgentFactory
from swarmmind.models.capability import AgentRole, ToolGroup
from swarmmind.models.run import Run
from swarmmind.models.task import SubTask, Task
from swarmmind.prompt_template import load_prompt_template, render_prompt_template


class Planner:
    """Create a simple task graph from the submitted goal."""

    def __init__(
        self,
        model_name: str = "gpt-4o",
        model_api_key: str | None = None,
        model_base_url: str | None = None,
        model_temperature: float = 0.2,
        model_max_tokens: int = 2048,
        system_prompt_template_name: str = "planner_system_v1.txt",
        user_prompt_template_name: str = "planner_task_decomposition_v1.md",
    ) -> None:
        self._model_name = model_name
        self._model_api_key = model_api_key
        self._model_base_url = model_base_url
        self._model_temperature = model_temperature
        self._model_max_tokens = model_max_tokens
        self._system_prompt_template_name = system_prompt_template_name
        self._user_prompt_template_name = user_prompt_template_name

    async def plan(self, task: Task, run: Run) -> list[SubTask]:
        """Return a task graph generated by model when available, with deterministic fallback."""
        llm_subtasks = await self._plan_with_model(task, run)
        if llm_subtasks:
            return llm_subtasks
        return self._plan_with_rules(task, run)

    async def _plan_with_model(self, task: Task, run: Run) -> list[SubTask] | None:
        if not self._model_name:
            return None
        if not self._model_api_key and not self._model_base_url:
            return None

        try:
            agent_factory = AgentFactory(
                AgentConfig(
                    name="planner-agent",
                    scope_config=AgentScopeConfig(
                        model_name=self._model_name,
                        api_key=self._model_api_key,
                        base_url=self._model_base_url,
                        temperature=self._model_temperature,
                        max_tokens=self._model_max_tokens,
                    ),
                    max_steps=6,
                    system_prompt=load_prompt_template(self._system_prompt_template_name),
                )
            )
            agent = agent_factory.create_main_agent(tools=[])
            prompt = self._compose_planning_prompt(task)
            result = await agent(Msg(name="user", role="user", content=prompt))
            text = result.get_text_content() or json.dumps(result.to_dict(), ensure_ascii=False)
            payload = self._extract_json_payload(text)
            if payload is None:
                return None

            plan_result = _PlanResult.model_validate(payload)
            return self._build_subtasks_from_plan(task, run, plan_result)
        except Exception:
            return None

    def _compose_planning_prompt(self, task: Task) -> str:
        return render_prompt_template(
            self._user_prompt_template_name,
            {
                "task_goal": task.goal,
                "constraints_json": json.dumps(task.constraints, ensure_ascii=False),
                "profile": str(task.metadata.get("profile", "py-basic")),
                "preferred_skill": str(task.metadata.get("preferred_skill") or "build_app"),
            },
        )

    @staticmethod
    def _extract_json_payload(raw_text: str) -> dict[str, object] | None:
        fenced = re.search(r"```(?:json)?\\s*(\{.*\})\\s*```", raw_text, flags=re.DOTALL | re.IGNORECASE)
        candidate = fenced.group(1) if fenced else raw_text
        start = candidate.find("{")
        end = candidate.rfind("}")
        if start == -1 or end == -1 or end < start:
            return None
        snippet = candidate[start : end + 1]
        try:
            value = json.loads(snippet)
        except json.JSONDecodeError:
            return None
        if isinstance(value, dict):
            return value
        return None

    def _build_subtasks_from_plan(self, task: Task, run: Run, plan_result: "_PlanResult") -> list[SubTask]:
        normalized: list[tuple[str, _PlanSubtaskSpec]] = []
        used_names: set[str] = set()

        for spec in plan_result.subtasks:
            normalized_name = self._normalize_name(spec.name)
            if not normalized_name:
                normalized_name = "subtask"
            base_name = normalized_name
            suffix = 2
            while normalized_name in used_names:
                normalized_name = f"{base_name}-{suffix}"
                suffix += 1
            used_names.add(normalized_name)
            normalized.append((normalized_name, spec))

        name_to_id = {name: str(uuid.uuid4()) for name, _ in normalized}
        subtasks: list[SubTask] = []

        for name, spec in normalized:
            role = self._parse_role(spec.role)
            tool_groups = self._parse_tool_groups(spec.required_tool_groups)
            if not tool_groups:
                tool_groups = self._default_tool_groups_for_role(role)

            dependencies = [name_to_id[d] for d in spec.dependencies if d in name_to_id and d != name]
            acceptance_criteria = [item.strip() for item in spec.acceptance_criteria if item.strip()]
            if not acceptance_criteria:
                acceptance_criteria = ["Subtask output is complete and verifiable."]

            subtasks.append(
                SubTask(
                    id=name_to_id[name],
                    task_id=task.id,
                    name=name,
                    description=spec.description.strip() or f"Execute {name}",
                    role=role,
                    preferred_skill=(spec.preferred_skill or task.metadata.get("preferred_skill") or "build_app"),
                    required_tool_groups=tool_groups,
                    sandbox_profile=spec.sandbox_profile or task.metadata.get("profile", "py-basic"),
                    acceptance_criteria=acceptance_criteria,
                    dependencies=dependencies,
                    metadata={
                        "run_id": run.id,
                        "plan_source": "llm",
                        "planning_prompt": self._user_prompt_template_name,
                    },
                )
            )

        return subtasks

    @staticmethod
    def _parse_role(value: str | None) -> AgentRole:
        if not value:
            return AgentRole.CODER
        try:
            return AgentRole(str(value).strip().lower())
        except ValueError:
            return AgentRole.CODER

    @staticmethod
    def _parse_tool_groups(values: list[str]) -> list[ToolGroup]:
        parsed: list[ToolGroup] = []
        for value in values:
            token = str(value).strip().lower()
            try:
                tool_group = ToolGroup(token)
            except ValueError:
                continue
            if tool_group not in parsed:
                parsed.append(tool_group)
        return parsed

    @staticmethod
    def _default_tool_groups_for_role(role: AgentRole) -> list[ToolGroup]:
        defaults = {
            AgentRole.PLANNER: [ToolGroup.PROJECT_READ],
            AgentRole.CODER: [ToolGroup.PROJECT_READ, ToolGroup.PROJECT_WRITE, ToolGroup.SANDBOX_EXEC],
            AgentRole.TESTER: [ToolGroup.SANDBOX_EXEC, ToolGroup.ARTIFACT_READ],
            AgentRole.REVIEWER: [ToolGroup.ARTIFACT_READ],
            AgentRole.RESEARCHER: [ToolGroup.WEB_SEARCH, ToolGroup.BROWSER_READ],
        }
        return defaults.get(role, [ToolGroup.PROJECT_READ])

    @staticmethod
    def _normalize_name(name: str) -> str:
        token = (name or "").strip().lower()
        token = re.sub(r"[^a-z0-9]+", "-", token)
        token = token.strip("-")
        return token

    def _plan_with_rules(self, task: Task, run: Run) -> list[SubTask]:
        goal = task.goal.lower()
        subtasks: list[SubTask] = []

        subtasks.append(
            SubTask(
                id=str(uuid.uuid4()),
                task_id=task.id,
                name="analyze-requirement",
                description="Analyze the goal and identify the implementation scope.",
                role=AgentRole.PLANNER,
                preferred_skill="task_planning",
                required_tool_groups=[ToolGroup.PROJECT_READ],
                acceptance_criteria=["The implementation scope is summarized clearly."],
                metadata={"run_id": run.id, "plan_source": "rules"},
            )
        )

        build_tool_groups = [ToolGroup.PROJECT_READ, ToolGroup.PROJECT_WRITE, ToolGroup.SANDBOX_EXEC]
        if "test" in goal:
            build_tool_groups.append(ToolGroup.ARTIFACT_READ)

        subtasks.append(
            SubTask(
                id=str(uuid.uuid4()),
                task_id=task.id,
                name="prepare-implementation",
                description=f"Prepare the implementation steps for: {task.goal}",
                role=AgentRole.CODER,
                preferred_skill=task.metadata.get("preferred_skill") or "build_app",
                required_tool_groups=build_tool_groups,
                sandbox_profile=task.metadata.get("profile", "py-basic"),
                acceptance_criteria=["The execution plan references the right tool groups."],
                metadata={"run_id": run.id, "plan_source": "rules"},
            )
        )

        if "test" in goal or "验证" in task.goal:
            subtasks.append(
                SubTask(
                    id=str(uuid.uuid4()),
                    task_id=task.id,
                    name="verify-result",
                    description="Verify the implementation using the declared acceptance criteria.",
                    role=AgentRole.TESTER,
                    preferred_skill="verification",
                    required_tool_groups=[ToolGroup.SANDBOX_EXEC, ToolGroup.ARTIFACT_READ],
                    sandbox_profile=task.metadata.get("profile", "py-basic"),
                    acceptance_criteria=["Verification evidence is attached to the run."],
                    metadata={"run_id": run.id, "plan_source": "rules"},
                )
            )

        return subtasks


class _PlanSubtaskSpec(BaseModel):
    name: str = Field(...)
    description: str = Field(default="")
    role: str = Field(default="coder")
    preferred_skill: str | None = Field(default=None)
    required_tool_groups: list[str] = Field(default_factory=list)
    sandbox_profile: str | None = Field(default=None)
    acceptance_criteria: list[str] = Field(default_factory=list)
    dependencies: list[str] = Field(default_factory=list)


class _PlanResult(BaseModel):
    subtasks: list[_PlanSubtaskSpec] = Field(default_factory=list)
