"""Build App Skill - Analyze, design, implement and test applications."""

from typing import Any
from swarmmind.skills.base import Skill, SkillResult


class BuildAppSkill(Skill):
    """Skill for building applications."""

    name = "build_app"
    description = "Build a complete application with code generation and testing"

    def __init__(self, sandbox_manager=None, file_tool=None):
        super().__init__()
        self._sandbox_manager = sandbox_manager
        self._file_tool = file_tool

    def get_parameters_schema(self) -> dict[str, Any]:
        """Get parameters schema."""
        return {
            "type": "object",
            "properties": {
                "app_type": {
                    "type": "string",
                    "enum": ["cli", "web", "api", "script"],
                    "description": "Type of application to build",
                },
                "language": {
                    "type": "string",
                    "enum": ["python", "javascript", "typescript"],
                    "default": "python",
                    "description": "Programming language",
                },
                "requirements": {
                    "type": "string",
                    "description": "Application requirements",
                },
                "output_dir": {
                    "type": "string",
                    "default": "output",
                    "description": "Output directory",
                },
            },
            "required": ["requirements"],
        }

    async def execute(self, **kwargs) -> SkillResult:
        """Execute the skill."""
        app_type = kwargs.get("app_type", "cli")
        language = kwargs.get("language", "python")
        requirements = kwargs.get("requirements", "")
        output_dir = kwargs.get("output_dir", "output")

        if not requirements:
            return SkillResult(success=False, error="Requirements are required")

        try:
            results = {
                "app_type": app_type,
                "language": language,
                "files": [],
            }

            # Step 1: Generate code
            code_files = self._generate_code(app_type, language, requirements)
            results["files"] = list(code_files.keys())

            # Step 2: Write files
            if self._file_tool:
                for filename, content in code_files.items():
                    path = f"{output_dir}/{filename}"
                    await self._file_tool(path=path, content=content)

            # Step 3: Test in sandbox
            test_result = None
            if self._sandbox_manager:
                test_result = await self._run_tests(output_dir, language)

            return SkillResult(
                success=True,
                output={
                    "files": results["files"],
                    "test_result": test_result,
                },
                metadata={"steps": ["generate", "write", "test"]},
            )

        except Exception as e:
            return SkillResult(success=False, error=str(e))

    def _generate_code(self, app_type: str, language: str, requirements: str) -> dict[str, str]:
        """Generate application code."""
        files = {}

        if language == "python":
            if app_type == "cli":
                files["main.py"] = self._generate_cli_python(requirements)
                files["requirements.txt"] = "# Add dependencies here\n"
            elif app_type == "web":
                files["app.py"] = self._generate_web_python(requirements)
                files["requirements.txt"] = "flask>=2.0.0\n"

        return files

    def _generate_cli_python(self, requirements: str) -> str:
        """Generate Python CLI app."""
        return f'''#!/usr/bin/env python3
"""CLI Application generated by SwarmMind."""

import sys

def main():
    print("Hello from SwarmMind!")
    print("Requirements: {requirements}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
'''

    def _generate_web_python(self, requirements: str) -> str:
        """Generate Python web app."""
        return f'''#!/usr/bin/env python3
"""Web Application generated by SwarmMind."""

from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def index():
    return jsonify({{
        "message": "Hello from SwarmMind!",
        "requirements": "{requirements}"
    }})

if __name__ == "__main__":
    app.run(debug=True)
'''

    async def _run_tests(self, output_dir: str, language: str) -> str:
        """Run tests in sandbox."""
        # Simplified - just run the main file
        if self._sandbox_manager and language == "python":
            result = await self._sandbox_manager.run_command(
                f"cd {output_dir} && python main.py"
            )
            return result.stdout or result.stderr
        return "Tests not run"
